### ISSUE TITLE
APIFairy listing schemas that don't exist?

### ISSUE THREAD

**Issue by aderbas** [miguelgrinberg/APIFairy#44]
I'm not understanding what is happening. I created a folder for each module, I have two modules that have one to one relationship. The problem is that in the documentation APIFairy is putting more than one schema for the User and for the Project.

![image](https://user-images.githubusercontent.com/12519019/159279789-c6948e31-8ede-47e9-922c-3d32d209a9ef.png)

What is User1 and Project1 ?

I have only these classes: ``class UserSchema(ma.SQLAlchemySchema)``  and ``class ProjecSchema(ma.SQLAlchemySchema)``

UserSchema have this:
```python
from app.modules.project.schema import  ProjecSchema

    ...
    default_project = ma.Nested(
        ProjecSchema(only=("id", "tfs_id", "tfs_description")), many=False
    )
```

**Comment by miguelgrinberg** [comment]
I'm not seeing your code, but this has to be caused by you creating multiple instances for these two schemas. You have only two classes, but what counts is not the classes, but the instances of these classes that are created. If you have endpoints that use one instance of the class, and some other endpoints that use a different instances, then they are going to be considered separately.

**Comment by aderbas** [comment]
Thanks for the answer.
When I Nested one of the classes, it is understanding that it is another schema. For example. If I put Nested(ProjectSchema()) on UserSchema for ``default_project`` property like this:
```python
default_project = ma.Nested(
     ProjectSchema(only=("id",)), many=False
)
```
Whenever I use ``ma.Nested`` passing the schema and using the ``only=("fields",..)`` it will create another schema in the Schema list in the documentation? Is there any way I can hide the schema list from the documentation?

_Sorry the name "Project" was wrong in the picture._

**Comment by aderbas** [comment]
And I get the ``UserWarning`` at the terminal: ``UserWarning: Multiple schemas resolved to the name Project.``

**Comment by miguelgrinberg** [comment]
@aderbas Sorry, but I don't understand what you want to do. Your nested schemas are different, because you are including a subset of the fields. How can they be represented accurately without using a separate schema in the OpenAPI?

Given that you are using a different schema for the nested versions, you may want to consider creating two separate schema classes, one for the nested version with just the id, and another one for the complete representation.

**Comment by aderbas** [comment]
Sorry I may not be explaining it right, I'll try to figure just that part of my project.
```
|── app
|  |── modules
|  |  |── user 
|  |  |  └── schema.py
|  |  |
|  |  └── project 
|  |    └── schema.py
|  └── app.py
|...
```
I'm going to do just one example of Nested in my classes here:

* File: app/modules/project/schema.py
```python
from app.app import ma

class ProjectSchema(ma.SQLAlchemySchema):
	id = ma.auto_field(dump_only=True)
	project_description = ma.auto_field(required=True)
	is_active = ma.auto_field(dump_only=True)
	
```

* File: app/modules/user/schema.py

```python
from app.app import ma
from app.modules.project.schema import ProjectSchema
...

class UserSchema(ma.SQLAlchemySchema):
	id = ma.auto_field(dump_only=True)
	full_name = ma.auto_field(required=True)
	user_email = ma.auto_field(required=True)
	
	default_project = ma.Nested(
		ProjectSchema(only=("id",)), many=False
	)	

```
In the generated documentation, in the 'SCHEMAS' section it lists: _User_, _Project_ and _Project1_. I just followed the Marshmallow [documentation](https://marshmallow.readthedocs.io/en/stable/nesting.html)

**Comment by miguelgrinberg** [comment]
Yes, I do understand what you are saying. What I don't understand is how you expect the nested schema can be represented without using a separate schema. You have two variants that you decided to generate from the same Schema class, but these are two different schemas:

- `ProjectSchema()` is a schema that has 3 fields
- `ProjectSchema(only=('id',)) is a schema that has one field

You may think that these are one schema, but in terms of the API definition it's two, since they have different contents.
